openapi: 3.0.0
paths:
  /syscollector/{agent_id}/hardware:
    get:
      tags:
      - Syscollector
      summary: Get agent hardware
      description: Return the agent's hardware info. This information include cpu,
        ram, scan info among others
      operationId: api.controllers.syscollector_controller.get_hardware_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/select'
      responses:
        '200':
          description: Return a list of agent's hardware results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorHardware'
              example:
                data:
                  affected_items:
                  - cpu:
                      cores: 4
                      mhz: 1101
                      name: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
                    ram:
                      free: 12401548
                      total: 32852420
                      usage: 63
                    scan:
                      id: 0
                      time: '2021-05-28T12:16:14Z'
                    board_serial: HA16934652
                    agent_id: '001'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/hotfixes:
    get:
      tags:
      - Syscollector
      summary: Get agent hotfixes
      description: Return all hotfixes installed by Microsoft(R) in Windows(R) systems
        (KB... fixes)
      operationId: api.controllers.syscollector_controller.get_hotfix_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/hotfix'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return an agent's hotfix results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorHotfixes'
              example:
                data:
                  affected_items:
                  - hotfix: KB2978691
                    scan:
                      id: 1708048540
                      time: '2019-10-30T16:09:35Z'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/netaddr:
    get:
      tags:
      - Syscollector
      summary: Get agent netaddr
      description: Return the agent's network address info. This information include
        used IP protocol, interface, IP address  among others
      operationId: api.controllers.syscollector_controller.get_network_address_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/iface'
      - $ref: '#/components/parameters/proto'
      - $ref: '#/components/parameters/address'
      - $ref: '#/components/parameters/broadcast'
      - $ref: '#/components/parameters/netmask'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's network results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorNetwork'
              example:
                data:
                  affected_items:
                  - scan:
                      id: 0
                    address: 172.26.0.7
                    iface: eth0
                    netmask: 255.255.0.0
                    broadcast: 172.26.255.255
                    proto: ipv4
                    agent_id: 1
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/netiface:
    get:
      tags:
      - Syscollector
      summary: Get agent netiface
      description: Return the agent's network interface info. This information include
        rx, scan, tx info and some network information among others
      operationId: api.controllers.syscollector_controller.get_network_interface_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/adapter'
      - $ref: '#/components/parameters/typesys'
      - $ref: '#/components/parameters/state'
      - $ref: '#/components/parameters/mtu'
      - $ref: '#/components/parameters/tx.packets'
      - $ref: '#/components/parameters/rx.packets'
      - $ref: '#/components/parameters/tx.bytes'
      - $ref: '#/components/parameters/rx.bytes'
      - $ref: '#/components/parameters/tx.errors'
      - $ref: '#/components/parameters/rx.errors'
      - $ref: '#/components/parameters/tx.dropped'
      - $ref: '#/components/parameters/rx.dropped'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's network interfaces results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorInterface'
              example:
                data:
                  affected_items:
                  - rx:
                      bytes: 679529
                      dropped: 0
                      errors: 0
                      packets: 3638
                    scan:
                      id: 0
                      time: '2021-05-28T12:16:14Z'
                    tx:
                      bytes: 1326491
                      dropped: 0
                      errors: 0
                      packets: 3828
                    type: ethernet
                    name: eth0
                    mtu: 1500
                    state: up
                    mac: 02:42:ac:18:00:02
                    agent_id: '001'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/netproto:
    get:
      tags:
      - Syscollector
      summary: Get agent netproto
      description: Return the agent's routing configuration for each network interface
      operationId: api.controllers.syscollector_controller.get_network_protocol_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/iface'
      - $ref: '#/components/parameters/type_syscollector'
      - $ref: '#/components/parameters/gateway'
      - $ref: '#/components/parameters/dhcp'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's network protocol results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorProtocol'
              example:
                data:
                  affected_items:
                  - scan:
                      id: 0
                    gateway: 172.24.0.1
                    dhcp: enabled
                    iface: eth0
                    type: ipv4
                    agent_id: '001'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/os:
    get:
      tags:
      - Syscollector
      summary: Get agent OS
      description: Return the agent's OS info. This information include os information,
        architecture information among others of all agents
      operationId: api.controllers.syscollector_controller.get_os_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/select'
      responses:
        '200':
          description: Return a list of agent's OS results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorOS'
              example:
                data:
                  affected_items:
                  - os:
                      codename: focal
                      major: '20'
                      minor: '04'
                      name: Ubuntu
                      platform: ubuntu
                      version: 20.04.2 LTS (Focal Fossa)
                    scan:
                      id: 0
                      time: 22021-05-28T12:16:14Z
                    sysname: Linux
                    release: 5.8.0-45-generic
                    version: '#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021'
                    architecture: x86_64
                    hostname: wazuh-master
                    agent_id: '001'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/packages:
    get:
      tags:
      - Syscollector
      summary: Get agent packages
      description: Return the agent's packages info. This information include name,
        section, size, priority information of all packages among others
      operationId: api.controllers.syscollector_controller.get_packages_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/vendor'
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/architecture'
      - $ref: '#/components/parameters/file_format'
      - $ref: '#/components/parameters/package_version'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's packages results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorPackages'
              example:
                data:
                  affected_items:
                  - scan:
                      id: 0
                      time: '2021-05-28T11:16:15Z'
                    multiarch: same
                    description: GCC Quad-Precision Math Library
                    source: krb5
                    name: libquadmath0
                    architecture: amd64
                    vendor: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
                    size: 426
                    format: deb
                    version: 8.4.0-1ubuntu1~18.04
                    section: libs
                    priority: optional
                    agent_id: '002'
                    location: ''
                    install_time: ''
                  - scan:
                      id: 0
                      time: '2021-05-28T11:16:15Z'
                    multiarch: foreign
                    description: secure shell (SSH) client, for secure access to remote
                      machines
                    source: openssh
                    name: openssh-client
                    architecture: amd64
                    vendor: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
                    size: 4117
                    format: deb
                    version: 1:8.2p1-4ubuntu0.2
                    section: net
                    priority: standard
                    agent_id: '002'
                    location: ''
                    install_time: ''
                  - scan:
                      id: 0
                      time: '2021-05-28T11:16:16Z'
                    description: Foreign Function Interface for Python calling C code
                      - backend
                    source: python-cffi
                    name: lpython-cffi-backend
                    architecture: amd64
                    vendor: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
                    size: 210
                    format: deb
                    version: 1.14.0-1build1
                    section: python
                    priority: optional
                    agent_id: '002'
                    location: ''
                    install_time: ''
                  total_affected_items: 307
                  total_failed_items: 0
                  failed_items: []
                  message: All specified syscollector information was returned
                  error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/ports:
    get:
      tags:
      - Syscollector
      summary: Get agent ports
      description: Return the agent's ports info. This information include local IP,
        Remote IP, protocol information among others
      operationId: api.controllers.syscollector_controller.get_ports_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/pid'
      - $ref: '#/components/parameters/protocol'
      - $ref: '#/components/parameters/local.ip'
      - $ref: '#/components/parameters/local.port'
      - $ref: '#/components/parameters/remote.ip'
      - $ref: '#/components/parameters/tx_queue'
      - $ref: '#/components/parameters/state'
      - $ref: '#/components/parameters/process'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's packages results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorPorts'
              example:
                data:
                  affected_items:
                  - local:
                      ip: 127.0.0.11
                      port: 46841
                    remote:
                      ip: 0.0.0.0
                      port: 0
                    scan:
                      id: 0
                      time: '2021-05-28T11:16:14Z'
                    inode: 12387152
                    rx_queue: 0
                    protocol: tcp
                    pid: 0
                    tx_queue: 0
                    process: ''
                    agent_id: '001'
                  - local:
                      ip: 0.0.0.0
                      port: 1514
                    remote:
                      ip: 0.0.0.0
                      port: 0
                    scan:
                      id: 0
                      time: '2021-05-28T11:16:14Z'
                    state: listening
                    inode: 12397927
                    rx_queue: 0
                    protocol: tcp
                    pid: 0
                    tx_queue: 0
                    process: ''
                    agent_id: '001'
                  - local:
                      ip: 0.0.0.0
                      port: 1515
                    remote:
                      ip: 0.0.0.0
                      port: 0
                    scan:
                      id: 315935312
                      time: '2020-04-15T11:02:07Z'
                    state: listening
                    inode: 12397153
                    rx_queue: 0
                    protocol: tcp
                    tx_queue: 0
                    process: ''
                    agent_id: '001'
                  total_affected_items: 3
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
  /syscollector/{agent_id}/processes:
    get:
      tags:
      - Syscollector
      summary: Get agent processes
      description: Return the agent's processes info
      operationId: api.controllers.syscollector_controller.get_processes_info
      x-rbac-actions:
      - $ref: '#/x-rbac-catalog/actions/syscollector:read'
      parameters:
      - $ref: '#/components/parameters/pretty'
      - $ref: '#/components/parameters/wait_for_complete'
      - $ref: '#/components/parameters/agent_id'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/search'
      - $ref: '#/components/parameters/select'
      - $ref: '#/components/parameters/process_pid'
      - $ref: '#/components/parameters/process_state'
      - $ref: '#/components/parameters/ppid'
      - $ref: '#/components/parameters/egroup'
      - $ref: '#/components/parameters/euser'
      - $ref: '#/components/parameters/fgroup'
      - $ref: '#/components/parameters/process_name'
      - $ref: '#/components/parameters/nlwp'
      - $ref: '#/components/parameters/pgrp'
      - $ref: '#/components/parameters/priority'
      - $ref: '#/components/parameters/rgroup'
      - $ref: '#/components/parameters/ruser'
      - $ref: '#/components/parameters/sgroup'
      - $ref: '#/components/parameters/suser'
      - $ref: '#/components/parameters/query'
      - $ref: '#/components/parameters/distinct'
      responses:
        '200':
          description: Return a list of agent's processes results
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/AllItemsResponseSyscollectorProcesses'
              example:
                data:
                  affected_items:
                  - scan:
                      id: 0
                      time: 2021-05-28 12:16:15+00:00
                    nice: 0
                    name: bash
                    resident: 788
                    egroup: root
                    sgroup: root
                    euser: root
                    size: 996
                    tgid: 1
                    share: 729
                    rgroup: root
                    argvs: /scripts/entrypoint.sh nginx-lb 4.4
                    start_time: 1217866
                    stime: 0
                    vm_size: 3984
                    priority: 20
                    utime: 2
                    nlwp: 1
                    session: 1
                    processor: 2
                    pgrp: 1
                    suser: root
                    state: S
                    ppid: 0
                    cmd: bash
                    tty: 0
                    pid: '1'
                    fgroup: root
                    ruser: root
                    agent_id: '001'
                  total_affected_items: 1
                  total_failed_items: 0
                  failed_items: []
                message: All specified syscollector information was returned
                error: 0
        '400':
          $ref: '#/components/responses/ResponseError'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/PermissionDeniedResponse'
        '405':
          $ref: '#/components/responses/InvalidHTTPMethodResponse'
        '429':
          $ref: '#/components/responses/TooManyRequestsResponse'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          description: Human readable description to explain the result of the request
    AllItemsResponseSyscollectorHardware:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorHardware'
    AllItemsResponseSyscollectorHotfixes:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorHotfix'
    AllItemsResponseSyscollectorInterface:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorInterface'
    AllItemsResponseSyscollectorOS:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorOS'
    AllItemsResponseSyscollectorPackages:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorPackages'
    AllItemsResponseSyscollectorPorts:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorPorts'
    AllItemsResponseSyscollectorProcesses:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorProcess'
    AllItemsResponseSyscollectorProtocol:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorProtocol'
    AllItemsResponseSyscollectorNetwork:
      allOf:
      - $ref: '#/components/schemas/AllItemsResponse'
      - type: object
        required:
        - affected_items
        properties:
          affected_items:
            type: array
            description: Items that successfully applied the API call action
            items:
              $ref: '#/components/schemas/SyscollectorNetwork'
  responses:
    ResponseError:
      description: Response to report a bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Bad Request
            detail: '''{invalid_param}'' is not a ''{expected_type}''. Failed validating
              ''format'' in schema[''items'']: {''description'': ''{parameter_name}'',
              ''format'': ''{expected_format}'', ''minLength'': {expected_length},
              ''type'': ''{expected_type}'', ''x-scope'': ['''', ''#/components/parameters/{parameter_name}'']}'
    PermissionDeniedResponse:
      description: Response to report a permission denied request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
          example:
            title: Permission Denied
            detail: 'Permission denied: Resource type: *:*'
            remediation: Please, make sure you have permissions to execute the current
              request. For more information on how to set up permissions, please visit
              https://documentation.wazuh.com/4.9/user-manual/api/rbac/configuration.html
            error: 4000
            dapi_errors:
              unknown-node:
                error: 'Permission denied: Resource type: *:*'
    UnauthorizedResponse:
      description: Response to report an unauthorized request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Unauthorized
            detail: No authorization token provided
    InvalidHTTPMethodResponse:
      description: Response to report an invalid HTTP method
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Method Not Allowed
            detail: Specified method is invalid for this resource
    TooManyRequestsResponse:
      description: Maximum number of request per minute reached
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestError'
          example:
            title: Wazuh Error
            detail: Maximum number of requests per minute reached
            remediation: 'This limit can be changed in api.yaml file. More information
              here: https://documentation.wazuh.com/4.9/user-manual/api/security/configuration.html'
            code: 6001
  parameters:
    agent_id:
      in: path
      name: agent_id
      description: Agent ID. All possible values from 000 onwards
      required: true
      schema:
        $ref: '#/components/schemas/AgentID'
    file_format:
      in: query
      name: format
      description: Filter by file format. For example 'deb' will output deb files
      schema:
        type: string
        format: alphanumeric
    hotfix:
      in: query
      name: hotfix
      description: Filter by hotfix
      schema:
        type: string
    limit:
      in: query
      name: limit
      description: 'Maximum number of elements to return. Although up to 100.000 can
        be specified, it is recommended not to exceed 500 elements. Responses may
        be slower the more this number is exceeded. '
      schema:
        type: integer
        format: int32
        default: 500
        minimum: 1
        maximum: 100000
    name:
      in: query
      name: name
      description: Filter by name
      schema:
        type: string
        format: alphanumeric
    offset:
      in: query
      name: offset
      description: First element to return in the collection
      schema:
        type: integer
        format: int32
        default: 0
        minimum: 0
    pretty:
      in: query
      name: pretty
      description: Show results in human-readable format
      schema:
        type: boolean
        default: false
    process:
      in: query
      name: process
      description: Filter by process name
      schema:
        type: string
        format: alphanumeric
    query:
      in: query
      name: q
      description: Query to filter results by. For example q=&quot;status=active&quot;
      schema:
        type: string
    search:
      in: query
      name: search
      description: Look for elements containing the specified string. To obtain a
        complementary search, use '-' at the beginning
      schema:
        type: string
        format: search
    select:
      in: query
      name: select
      description: 'Select which fields to return (separated by comma). Use ''.''
        for nested fields. For example, ''{field1: field2}'' may be selected with
        ''field1.field2'''
      schema:
        type: array
        items:
          type: string
          format: names
    sort:
      in: query
      name: sort
      description: 'Sort the collection by a field or fields (separated by comma).
        Use +/- at the beggining to list in ascending or descending order. Use ''.''
        for nested fields. For example, ''{field1: field2}'' may be selected with
        ''field1.field2'''
      schema:
        type: string
        format: sort
    type_syscollector:
      in: query
      name: type
      description: Type of network
      schema:
        type: string
        format: alphanumeric
    typesys:
      in: query
      name: type
      description: Type of interface
      schema:
        type: string
    wait_for_complete:
      in: query
      name: wait_for_complete
      description: Disable timeout response
      schema:
        type: boolean
        default: false
    distinct:
      in: query
      name: distinct
      description: Look for distinct values.
      schema:
        type: boolean
        default: false
    proto:
      in: query
      name: proto
      description: Filter by IP protocol
      schema:
        type: string
        format: alphanumeric
    address:
      in: query
      name: address
      description: Filter by IP address
      schema:
        type: string
        format: alphanumeric
    broadcast:
      in: query
      name: broadcast
      description: Filter by broadcast direction
      schema:
        type: string
        format: alphanumeric
    netmask:
      in: query
      name: netmask
      description: Filter by netmask
      schema:
        type: string
        format: alphanumeric
    adapter:
      in: query
      name: adapter
      description: Filter by adapter
      schema:
        type: string
        format: alphanumeric
    state:
      in: query
      name: state
      description: Filter by state
      schema:
        type: string
        format: alphanumeric
    mtu:
      in: query
      name: mtu
      description: Filter by mtu
      schema:
        type: integer
        format: int32
        minimum: 0
    tx.packets:
      in: query
      name: tx.packets
      description: Filter by tx.packets
      schema:
        type: integer
        format: int32
        minimum: 0
    rx.packets:
      in: query
      name: rx.packets
      description: Filter by rx.packets
      schema:
        type: integer
        format: int32
        minimum: 0
    tx.bytes:
      in: query
      name: tx.bytes
      description: Filter by tx.bytes
      schema:
        type: integer
        format: int32
        minimum: 0
    rx.bytes:
      in: query
      name: rx.bytes
      description: Filter by rx.bytes
      schema:
        type: integer
        format: int32
        minimum: 0
    tx.errors:
      in: query
      name: tx.errors
      description: Filter by tx.errors
      schema:
        type: integer
        format: int32
        minimum: 0
    rx.errors:
      in: query
      name: rx.errors
      description: Filter by rx.errors
      schema:
        type: integer
        format: int32
        minimum: 0
    tx.dropped:
      in: query
      name: tx.dropped
      description: Filter by tx.dropped
      schema:
        type: integer
        format: int32
        minimum: 0
    rx.dropped:
      in: query
      name: rx.dropped
      description: Filter by rx.dropped
      schema:
        type: integer
        format: int32
        minimum: 0
    iface:
      in: query
      name: iface
      description: Filter by network interface
      schema:
        type: string
        format: alphanumeric
    gateway:
      in: query
      name: gateway
      description: Filter by network gateway
      schema:
        type: string
        format: alphanumeric
    dhcp:
      in: query
      name: dhcp
      description: Filter by network dhcp (enabled or disabled)
      schema:
        $ref: '#/components/schemas/DHCPStatus'
    architecture:
      in: query
      name: architecture
      description: Filter by architecture
      schema:
        type: string
        format: alphanumeric
    vendor:
      in: query
      name: vendor
      description: Filter by vendor
      schema:
        type: string
    pid:
      in: query
      name: pid
      description: Filter by pid
      schema:
        type: string
        format: numbers
    protocol:
      in: query
      name: protocol
      description: Filter by protocol
      schema:
        type: string
        format: alphanumeric
    local.ip:
      in: query
      name: local.ip
      description: Filter by Local IP
      schema:
        type: string
        format: alphanumeric
    local.port:
      in: query
      name: local.port
      description: Filter by Local Port
      schema:
        type: string
        format: numbers
    remote.ip:
      in: query
      name: remote.ip
      description: Filter by Remote IP
      schema:
        type: string
        format: alphanumeric
    tx_queue:
      in: query
      name: tx_queue
      description: Filter by tx_queue
      schema:
        type: string
        format: numbers
    process_pid:
      in: query
      name: pid
      description: Filter by process pid
      schema:
        type: string
        format: numbers
    process_state:
      in: query
      name: state
      description: Filter by process state
      schema:
        type: string
        format: alphanumeric
    ppid:
      in: query
      name: ppid
      description: Filter by process parent pid
      schema:
        type: string
        format: numbers
    egroup:
      in: query
      name: egroup
      description: Filter by process egroup
      schema:
        type: string
        format: alphanumeric
    euser:
      in: query
      name: euser
      description: Filter by process euser
      schema:
        type: string
        format: alphanumeric
    fgroup:
      in: query
      name: fgroup
      description: Filter by process fgroup
      schema:
        type: string
        format: alphanumeric
    process_name:
      in: query
      name: name
      description: Filter by process name
      schema:
        type: string
        format: alphanumeric
    nlwp:
      in: query
      name: nlwp
      description: Filter by process nlwp
      schema:
        type: string
        format: numbers
    pgrp:
      in: query
      name: pgrp
      description: Filter by process pgrp
      schema:
        type: string
        format: numbers
    priority:
      in: query
      name: priority
      description: Filter by process priority
      schema:
        type: string
        format: numbers
    rgroup:
      in: query
      name: rgroup
      description: Filter by process rgroup
      schema:
        type: string
        format: alphanumeric
    ruser:
      in: query
      name: ruser
      description: Filter by process ruser
      schema:
        type: string
        format: alphanumeric
    sgroup:
      in: query
      name: sgroup
      description: Filter by process sgroup
      schema:
        type: string
        format: alphanumeric
    suser:
      in: query
      name: suser
      description: Filter by process suser
      schema:
        type: string
        format: alphanumeric
    package_version:
      in: query
      name: version
      description: Filter by package version
      schema:
        type: string
